name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Python unit tests
      run: python3 -u -m unittest tests/tests.py

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile

    - name: Integration test
      id: integration
      uses: ./
      with:
        path-to-root: tests
        base-url-path: https://TESTING.FAKE.WEB.ADDRESS.TESTING/

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.integration.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.integration.outputs.url-count }}"
        echo "excluded-count = ${{ steps.integration.outputs.excluded-count }}"

    - name: Verify integration test results
      run: python3 -u -m unittest tests/integration.py
